name: Publish to PyPI

on:
  push:
    branches:
      - main  # Change to your default branch if it's not named "main"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install cibuildwheel
      run: python -m pip install cibuildwheel

    - name: Build wheels for Python 3.10 and newer
      env:
        CIBW_BUILD: 'cp3[10-9]*'
      run: python -m cibuildwheel --output-dir dist

    - name: Publish to PyPI
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@v1.4.2
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
