name: Publish to PyPI

on:
  push:
    branches:
      - main  # Triggered every time you push to the "main" branch

jobs:
  build_and_publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install build tools and dependencies
      run: |
        python -m pip install --upgrade pip build

    - name: Build sdist and wheel using 'build'
      run: python -m build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}


